### ISSUE TITLE
Can't open a movie or tv show

### ISSUE THREAD

**Issue by adrianocart** [PopcornTV/node-images#5]
Hello everyone.

I'm finding error when I try to watch any content. Everything feels like working find and I can see the grid of movies but when I choose one still keep loading. In terminal I can see the message below.

Thanks.

error: uncaughtException: Can't load the addon. Issue to: https://github.com/PopcornTV/node-images/issues 
{ date: 'Sun Oct 04 2015 17:51:58 GMT-0300 (BRT)',
  process: 
   { pid: 17117,
     uid: 0,
     gid: 0,
     cwd: '/Users/Adriano/Desktop/PopcornTV',
     execPath: '/usr/local/bin/node',
     version: 'v4.1.1',
     argv: 
      [ '/usr/local/bin/node',
        '/Users/Adriano/Desktop/PopcornTV/atv.js' ],
     memoryUsage: { rss: 52023296, heapTotal: 28900608, heapUsed: 25958888 } },
  os: 
   { loadavg: [ 1.595703125, 1.48095703125, 1.58251953125 ],
     uptime: 807398 },
  trace: 
   [ { column: 7,
       file: '/Users/Adriano/Desktop/PopcornTV/node_modules/ptv-images/binding.js',
       function: '',
       line: 61,
       method: null,
       native: false },
     { column: 26,
       file: 'module.js',
       function: 'Module._compile',
       line: 434,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 452,
       method: 'Module._extensions..js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 355,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 310,
       method: 'Module._load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 365,
       method: 'require',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'require',
       line: 384,
       method: null,
       native: false },
     { column: 15,
       file: '/Users/Adriano/Desktop/PopcornTV/node_modules/ptv-images/index.js',
       function: '',
       line: 4,
       method: null,
       native: false },
     { column: 26,
       file: 'module.js',
       function: 'Module._compile',
       line: 434,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 452,
       method: 'Module._extensions..js',
       native: false } ],
  stack: 
   [ 'Error: Can\'t load the addon. Issue to: https://github.com/PopcornTV/node-images/issues',
     '    at Object.<anonymous> (/Users/Adriano/Desktop/PopcornTV/node_modules/ptv-images/binding.js:61:7)',
     '    at Module._compile (module.js:434:26)',
     '    at Object.Module._extensions..js (module.js:452:10)',
     '    at Module.load (module.js:355:32)',
     '    at Function.Module._load (module.js:310:12)',
     '    at Module.require (module.js:365:17)',
     '    at require (module.js:384:17)',
     '    at Object.<anonymous> (/Users/Adriano/Desktop/PopcornTV/node_modules/ptv-images/index.js:4:15)',
     '    at Module._compile (module.js:434:26)',
     '    at Object.Module._extensions..js (module.js:452:10)' ] }
error: Error: Can't load the addon. Issue to: https://github.com/PopcornTV/node-images/issues
    at Object.<anonymous> (/Users/Adriano/Desktop/PopcornTV/node_modules/ptv-images/binding.js:61:7)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Adriano/Desktop/PopcornTV/node_modules/ptv-images/index.js:4:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by cyberaver** [comment]
I am getting the exact same error.- Let me know how to solve it.

**Comment by OstlerDev** [comment]
Downgrade to a node version of 0.12.x or disable fanart in the settings. This is an issue I hope to fix soon.

**Comment by cyberaver** [comment]
Can you let me know the procedure of any of the solutions? great work! thanks from Uruguay

**Comment by OstlerDev** [comment]
Uninstall your current version of node, then install a node version of 0.12.x.

**Comment by cyberaver** [comment]
I have disable the fanart in the setting but didn't work.= don't know how to downgrade the node version.... hope this is fixed soon.
thanks anyway

**Comment by OstlerDev** [comment]
I hope to fix it sometime soon, but all my time currently is going to either the native version of PopcornTV or to school/work.

**Comment by OstlerDev** [comment]
fixed in last pull.
